-- WHAT THE GOLF? Archipelago map tracker.
-- Everything under items/, locations/, maps/ and layouts/ is GENERATED by
-- tools/build_poptracker.py from the apworld's own data.py, so location names
-- can never drift from the seed. Edit tools/poptracker_src/ instead.

print("-- WHAT THE GOLF? AP tracker (variant " .. tostring(Tracker.ActiveVariantUID) .. ") --")

Tracker:AddItems("items/keys.json")
Tracker:AddItems("items/settings.json")
Tracker:AddItems("items/progress.json")

Tracker:AddMaps("maps/maps.json")

-- main.json holds the holes AND the crown chests: they share the sub-area parent
-- nodes, and PopTracker would rename a second node of the same name to "X[1]".
Tracker:AddLocations("locations/main.json")
Tracker:AddLocations("locations/episodes.json")

Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/maps.json")
Tracker:AddLayouts("layouts/broadcast.json")
Tracker:AddLayouts("layouts/settings.json")
Tracker:AddLayouts("layouts/tracker.json")

ScriptHost:LoadScript("scripts/wtg_data.lua")
ScriptHost:LoadScript("scripts/logic.lua")

if Archipelago then
    ScriptHost:LoadScript("scripts/autotracking.lua")
    ScriptHost:LoadScript("scripts/autotab.lua")
end
